version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5435:5432
    volumes:
      - my_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=leanghuy
      - POSTGRES_DB=expense_tracking_db

  spring-app:
    image: "spring_image"
    build:
      context: .
    container_name: spring_app
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=leanghuy
      - POSTGRES_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/expense_tracking_db
      - SPRING_DATASOURCE_USERNAME=leanghuy
      - SPRING_DATASOURCE_PASSWORD=1234

    ports:
      - "8082:8080"

volumes:
  my_volume:
